### ISSUE TITLE
error upon initial installation

### ISSUE THREAD

**Issue by tinkerernoob** [baumlin/raspberrypi#1]
download file - fine, saved
open directory - fine
python setup.py install - error

unable to execute '/var/lib/jenkins/LE/build5/workspace/RPi4/build.LibreELEC-RPi4.arm-9.2.1/toolchain/bin/host-gcc': No such file or directory
error: command '/var/lib/jenkins/LE/build5/workspace/RPi4/build.LibreELEC-RPi4.arm-9.2.1/toolchain/bin/host-gcc' failed with exit status 1

Using Raspberry Pi 4B LibreElec v9.2.1 (Kernel: Linux 4.19.106)
Build: Kodi 18.6 Git:Leia_pi4_18.6-Leia

**Comment by baumlin** [comment]
Try installing the **Rasperry Pi Tools** Add-on first
